.github/workflows/deploy.yml
.gitignore
Dockerfile
build.gradle
docker-compose.yml
src/main/resources/application-prod.yml
src/main/resources/application.properties
src/main/resources/application.yml

closed #1 
1. main 혹은 develop 브랜치 push/PR 발생 시 트리거
2. GitHub Actions의 build-docker-image Job 시작
- Gradle로 bootJar 빌드
- EC2에 /home/ubuntu/deploy 폴더 생성
- docker-compose.yml 전송
- Docker 이미지 빌드 → Hub에 Push
3. deploy Job 실행
- EC2에 SSH 접속
- .env 파일 생성 및 환경변수 주입
- 기존 컨테이너 중지 및 이미지 Pull
- 새 컨테이너로 재기동 (up -d --force-recreate)
- 미사용 이미지 정리 (image prune)

[FEATURE] CICD 파이프라인 구축

---

src/main/java/org/lxdproject/lxd/notification/entity/Notification.java
src/main/java/org/lxdproject/lxd/notification/entity/enums/NotificationType.java
src/main/java/org/lxdproject/lxd/notification/entity/enums/TargetType.java

closed #23 
알림과 관련 enum을 추가했습니다.
사용자 연관관계까지 포함합니다.
`Notification`: 알림 엔티티
`NotificationType`: 알림의 타입종류(댓글, 좋아요, 친구요청, 교정)
`TargetType`: 대상 유형(일기, 댓글, 멤버)

[FEATURE] Notification Entity 생성

---

src/main/java/org/lxdproject/lxd/member/entity/Member.java

closed #26 
Member 엔티티 수정
1. BaseEntity 상속
2. username 필드에 unique 속성 추가

[FEATURE] Member 엔티티 수정

---

.github/workflows/deploy.yml

related #1 
.env 파일 누적 문제 해결
Docker Build & Push 순서 재배치
- docker login을 먼저 하고 docker build → push를 하도록 순서 재정렬
- 이전에는 build → login → push인데, login을 먼저 해서 인증 오류 방지
cat << EOF > .env 형태로 초기화 후 작성
- .env 파일을 >>로 계속 append하고 있는데, action을 반복 실행하면서 중복으로 들어가는 문제가 발생함

[FIX] .env 파일을 >>로 계속 append 하여 중복되는 문제 해결

---

src/main/java/org/lxdproject/lxd/diary/entity/Diary.java
src/main/java/org/lxdproject/lxd/diary/entity/mapping/DiaryLike.java
src/main/java/org/lxdproject/lxd/member/entity/Member.java

closed #29 
- Diary, Member 연관관계 설정
- Diary, Member, DiaryLikes 엔티티 수정

refactor: Diary, Member 엔티티 연관관계 양방향 매핑 설정

---

build.gradle

closed #59 
- `build.gradle`에 QueryDSL 설정을 추가했습니다. 
- `build.gradle` 파일 수정
- 혹시 빌드 오류 발생 시에는 에디터에서 다음 설정들을 진행하셨는지 확인 부탁드립니다! (사진은 InteliJ 기준)

[CHORE] QueryDSL 설정 추가

---

src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
src/main/java/org/lxdproject/lxd/config/AwsS3Config.java
src/main/java/org/lxdproject/lxd/config/security/SecurityConfig.java
src/main/java/org/lxdproject/lxd/diary/controller/DiaryApi.java
src/main/java/org/lxdproject/lxd/diary/controller/DiaryController.java
src/main/java/org/lxdproject/lxd/diary/entity/Diary.java
src/main/java/org/lxdproject/lxd/diary/entity/Question.java
src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java

closed #61
- 특이사항) `AwsS3Config` 파일과 yml 파일의 변수명 위치가 서로 일치하지 않아서 수정했습니다. 
- 로그인 한 사용자의 JWT 토큰의 Payload의 userId 추출 후 일기 작성자의 userId와 비교해서 작성자가 수정중인지 확인하고 다를 시 예외 처리
- 존재하는 일기를 수정중인지 검사하고 존재하지 않는 일기라면 예외처리
- 일기 수정 기능 구현
- 스웨거 코드 작성
- ErrorStatus, Diary, ... 파일 수정

[FEATURE] 내가 작성한 일기 수정 API 구현

---

src/main/java/org/lxdproject/lxd/diarycomment/controller/DiaryCommentApi.java
src/main/java/org/lxdproject/lxd/diarycomment/controller/DiaryCommentController.java
src/main/java/org/lxdproject/lxd/diarycomment/dto/DiaryCommentDeleteResponseDTO.java
src/main/java/org/lxdproject/lxd/diarycomment/dto/DiaryCommentRequestDTO.java
src/main/java/org/lxdproject/lxd/diarycomment/dto/DiaryCommentResponseDTO.java
src/main/java/org/lxdproject/lxd/diarycomment/entity/DiaryComment.java
src/main/java/org/lxdproject/lxd/diarycomment/repository/DiaryCommentRepository.java
src/main/java/org/lxdproject/lxd/diarycomment/service/DiaryCommentService.java
src/main/java/org/lxdproject/lxd/diarycommentlike/repository/DiaryCommentLikeRepository.java
src/main/java/org/lxdproject/lxd/diarycommentlike/service/DiaryCommentLikeService.java

closed #70 
일기 댓글 조회/삭제 API를 구현했습니다
-일기 댓글 조회 API 구현
-일기 댓글 삭제 API 구현
-일기 댓글 entity수정
-일기 댓글 좋아요 entity수정

[FEATURE] 일기 댓글 조회/삭제 API 구현

---

src/main/java/org/lxdproject/lxd/auth/controller/AuthRestController.java
src/main/java/org/lxdproject/lxd/auth/dto/AuthRequestDTO.java
src/main/java/org/lxdproject/lxd/auth/dto/AuthResponseDTO.java
src/main/java/org/lxdproject/lxd/auth/dto/oauth/GoogleTokenResponse.java
src/main/java/org/lxdproject/lxd/auth/dto/oauth/GoogleUserInfo.java
src/main/java/org/lxdproject/lxd/auth/dto/oauth/OAuthUserInfo.java
src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
src/main/java/org/lxdproject/lxd/auth/service/oauth/GoogleOAuthClient.java
src/main/java/org/lxdproject/lxd/auth/service/oauth/OAuthClient.java
src/main/java/org/lxdproject/lxd/config/RestTemplateConfig.java
src/main/java/org/lxdproject/lxd/config/security/SecurityConfig.java
src/main/java/org/lxdproject/lxd/member/converter/MemberConverter.java
src/main/java/org/lxdproject/lxd/member/dto/MemberRequestDTO.java

closed #72 
Google OAuth2 로그인 API 구현
- 프론트에서 전달받은 code를 이용하여 access token 발급 및 사용자 정보 요청 구현
- 신규 유저 여부를 판단하는 isNewMember 변수 반환
- 구글과 관련된 환경 변수 설정은 Notion 내 공유된 local-application.yml 에 올려둬서 이 부분 참고
- 추후 프론트엔드 URI 확정 시, Google Cloud OAuth 승인 URI/리다이렉트 URI 및 yml 파일 수정 필요

[FEATURE] 구글 로그인 구현

---

src/main/java/org/lxdproject/lxd/correction/controller/CorrectionApi.java
src/main/java/org/lxdproject/lxd/correction/controller/CorrectionRestController.java
src/main/java/org/lxdproject/lxd/correction/dto/CorrectionResponseDTO.java
src/main/java/org/lxdproject/lxd/correction/dto/MemberSavedCorrectionRequestDTO.java
src/main/java/org/lxdproject/lxd/correction/entity/Correction.java
src/main/java/org/lxdproject/lxd/correction/repository/CorrectionRepository.java
src/main/java/org/lxdproject/lxd/correction/repository/MemberSavedCorrectionRepository.java
src/main/java/org/lxdproject/lxd/correction/service/CorrectionService.java
src/main/java/org/lxdproject/lxd/correction/service/MemberSavedCorrectionService.java
src/main/java/org/lxdproject/lxd/diarycomment/service/DiaryCommentService.java

closed #64 
교정 좋아요 API 구현
- 교정 좋아요 (toggle 포함) 구현

[FEATURE] 교정 좋아요 API 구현

---

src/main/java/org/lxdproject/lxd/auth/dto/AuthRequestDTO.java

closed #72 
@NoArgsConstructor 추가
@NoArgsConstructor 추가

[FIX] @NoArgsConstructor 추가

---

src/main/java/org/lxdproject/lxd/correction/controller/CorrectionApi.java
src/main/java/org/lxdproject/lxd/correction/controller/CorrectionRestController.java
src/main/java/org/lxdproject/lxd/correction/service/CorrectionService.java

closed #87 
- 교정 @AuthenticationPrincipal 수정
- 교정 API 내에 @AuthenticationPrincipal를 제거하고, Security Util 활용으로 변경하였습니다.

[FIX] 교정 Auth 오류 수정

---

src/main/java/org/lxdproject/lxd/auth/controller/AuthApi.java
src/main/java/org/lxdproject/lxd/auth/controller/AuthController.java
src/main/java/org/lxdproject/lxd/auth/dto/AuthRequestDTO.java

closed #95 
Swagger 정리를 위한 AuthApi 도입
- AuthApi 구현 및 AuthController에 연결
- 누락된 @Schema 작성

[REFACTOR] AuthApi 도입

---

src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
src/main/java/org/lxdproject/lxd/auth/controller/AuthApi.java
src/main/java/org/lxdproject/lxd/auth/controller/AuthController.java
src/main/java/org/lxdproject/lxd/auth/dto/AuthRequestDTO.java
src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
src/main/java/org/lxdproject/lxd/config/security/SecurityConfig.java
src/main/java/org/lxdproject/lxd/config/security/jwt/JwtAuthenticationFilter.java
src/main/java/org/lxdproject/lxd/config/security/jwt/JwtTokenProvider.java

closed #151 
로그아웃 API 구현 및 일부 외부 API 수정
- 로그아웃 기능 구현
- 리프레쉬 토큰 유효성 검사 
- redis에서 해당 리프레쉬 토큰 제거
- 로그인 시, 액세스 토큰이 아닌 리프레쉬 토큰으로 요청하면 에러 처리
- 로그인 시, 소셜 로그인 계정으로 시도할 경우 적절한 에러 응답 메시지로 수정

[FEATURE] logout API 구현

---

src/main/java/org/lxdproject/lxd/config/security/SecurityConfig.java

develop 브랜치로 액션이 트리거 되었을 때 동일하게 cors 설정이 반영되도록 함

Chore: develop 브랜치에 main과 동일한 cors 설정 반영

---

src/main/java/org/lxdproject/lxd/config/security/SecurityConfig.java
src/main/java/org/lxdproject/lxd/diary/dto/DiarySummaryResponseDTO.java
src/main/java/org/lxdproject/lxd/diary/dto/MyDiarySummaryResponseDTO.java
src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepositoryImpl.java

[RELEASE] 코드래빗 리뷰사항 반영

---

src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
src/main/java/org/lxdproject/lxd/member/entity/Member.java
src/main/java/org/lxdproject/lxd/member/service/MemberService.java

closed #187 
unique 설정을 제거
회원가입 및 회원정보수정 시 닉네임 고유값인지 검사하는 코드 제거
스키마 로컬/배포 환경 반영 완료

[FEAT] 닉네임의 unique 설정 및 검사 제거

---

src/main/java/org/lxdproject/lxd/diary/dto/DiarySummaryResponseDTO.java
src/main/java/org/lxdproject/lxd/diary/dto/MemberDiarySummaryResponseDTO.java
src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepositoryCustom.java
src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepositoryImpl.java
src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java

closed #203 
- 사용자 정보란에 모국어, 학습언어 추가하기
- `DiaryService`, `MemberDiarySummaryResponseDTO`, ...

[FEATURE] 사용자 정보란에 모국어, 학습언어 추가하기

---

src/main/java/org/lxdproject/lxd/notification/service/NotificationService.java

closed #245 
messageResolverManager로 메시지 parts 생성시 멤버의 system language로 getter 수정

[FIX] 멤버의 system language로 알림 메시지 언어 설정

---

src/main/java/org/lxdproject/lxd/auth/service/AuthService.java

Fix: 디버깅 에러 수정

---

src/main/java/org/lxdproject/lxd/friend/repository/FriendRepositoryCustom.java
src/main/java/org/lxdproject/lxd/friend/repository/FriendRepositoryImpl.java
src/main/java/org/lxdproject/lxd/friend/service/FriendService.java

[RELEASE] 친구 관계 버그 수정사항 반영

---

src/main/java/org/lxdproject/lxd/diary/dto/DiaryDetailResponseDTO.java
src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java

- closed #275 
일기 상세조회시 좋아요 여부 필드 누락 해결
DiaryDetailResponse의 from 메소드를 하나로 통합하여 DiaryService에 적용함

[FIX] 일기 상세조회시 좋아요 여부 필드 추가

---

src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
src/main/java/org/lxdproject/lxd/infra/redis/RedisService.java

closed #278 
redis 이메일 조회 전 redis 값이 존재하는 지 검사하는 로직 추가
redis 이메일 조회 전 redis 값이 존재하는 지 검사하는 로직 추가

[FIX] redis 이메일 조회 시 발생하는 에러 처리

---

src/main/java/org/lxdproject/lxd/auth/service/AuthService.java

closed #279 
비밀번호 변경을 위한 이메일 인증 후 리다이렉트 uri 변경
비밀번호 변경을 위한 이메일 인증 후 리다이렉트 uri 변경

[FEAT] 비밀번호 변경을 위한 이메일 인증 후 리다이렉트 uri 변경
